### ISSUE TITLE
Ruby-Sass converts color values to shorter representations, LibSass doesn't

### ISSUE THREAD

**Issue by bittner** [sass-compatibility/sass-compatibility.github.io#47]
I've just switched from `gulp-ruby-sass` to `gulp-sass`, simply for the issue of CSS inline imports ([sass/#556](https://github.com/sass/sass/issues/556), [sass-loader/#101](https://github.com/jtangelder/sass-loader/issues/101)). And, yes, inline-importing CSS files works like a charm with the LibSass-based implementation. This is one "incompatibility". :smirk:

Comparing the generated CSS I see that the LibSass-generated file is slightly bigger, because of color values that are kind if "minified" by the Ruby implementation, whereas with LibSass they remain as they are in the original source file (`.sass`), e.g.

# original = LibSass --> Ruby-Sass
* `#ffffcc` --> `#ffc`
* `#CC0000` --> `#c00`
* `#FF0000` --> `red`
* `#AAAAAA` --> `#aaa`
* `#99CC66` --> `#9c6`
* `#FF6600` --> `#f60`
* `#CC3300` --> `#c30`
* `#330099` --> `#309`
* `#336666` --> `#366`
* `#003333` --> `#033`
* `#CC3300` --> `#c30`

Interestingly, not all color values are converted, some remain unchanged, e.g.

* `#FFCCCC` (but this occurs in a `background-color`, not in `color`)
* `#006699` (`color`)
* `#00AA88` (`color`)
* `#CC0000` (`color`, even though converted earlier in the document in a `border` -- see above)

Is this an incompatibility I'm supposed to give notice about, or is this behavior maybe configurable in LibSass? I'd love to see the output matching completely.

**Comment by HugoGiraudel** [comment]
Ping @xzyfer for opinion. :)

**Comment by xzyfer** [comment]
LibSass does do this. Like Ruby sass it only happens in compressed mode. In
other modes it substitutes color values for names if possible.

**Comment by HugoGiraudel** [comment]
Soooo no incompatibility, right?

**Comment by xzyfer** [comment]
Not as far as I know.

**Comment by HugoGiraudel** [comment]
Closing then, thanks!

**Comment by bittner** [comment]
Sorry, but this is not true. My observation is about compressed mode. You have to reopen this bug. Sass packages involved are:
```
├─┬ gulp-sass@2.1.0
│ ├─┬ node-sass@3.4.1
```

**Comment by xzyfer** [comment]
Please provide a sassmiester gist showing an example. The code for this
definitely exists but it's entirely possible there is a bug.

**Comment by bittner** [comment]
Here is the SassMeister gist: [bittner/SassMeister-input.scss](https://gist.github.com/bittner/11c6ec2bb694b7026955)
Don't blame me for the syntax, I've noted the source of the code in the header comments.

**Comment by xzyfer** [comment]
This is a bug in recent versions, but the feature exists.

**Comment by xzyfer** [comment]
LibSass bug https://github.com/sass/libsass/issues/1733
